spring.application.name=smart-maintenance
spring.datasource.url=jdbc:mysql://localhost:3306/smart_maintenance
spring.datasource.username=root
spring.datasource.password=Sql@123@123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true